@echo off
title Deribit Depth — Local Server
color 0A

:: ── Check Node.js ────────────────────────────────────────────────────────────
where node >nul 2>&1
if errorlevel 1 (
    echo.
    echo  [ERROR] Node.js is not installed or not in your PATH.
    echo.
    echo  Please install it:
    echo    1. Go to https://nodejs.org
    echo    2. Download the LTS version
    echo    3. Run the installer (keep all defaults)
    echo    4. Close this window and run start-server.bat again
    echo.
    pause
    exit /b 1
)

echo  [OK] Node.js found:
node --version

:: ── Install dependencies ──────────────────────────────────────────────────────
if not exist "node_modules\" (
    echo.
    echo  Installing dependencies (express, cors, dotenv)...
    call npm install
    if errorlevel 1 (
        echo  [ERROR] npm install failed.
        pause
        exit /b 1
    )
    echo  [OK] Dependencies installed.
)

:: ── Create .env if missing ────────────────────────────────────────────────────
if not exist ".env" (
    echo.
    echo  No .env file found — creating one with a fresh ENCRYPTION_KEY...
    for /f "delims=" %%K in ('node -e "process.stdout.write(require('crypto').randomBytes(32).toString('hex'))"') do set NEWKEY=%%K
    (
        echo # Auto-generated by start-server.bat
        echo ENCRYPTION_KEY=%NEWKEY%
    ) > .env
    echo  [OK] .env created with ENCRYPTION_KEY.
) else (
    echo  [OK] .env file found.
)

:: ── Start server ──────────────────────────────────────────────────────────────
echo.
echo  Starting server on http://localhost:3000 ...
echo  Keep this window open while using the API Keys tab.
echo  Press Ctrl+C to stop the server.
echo.
node server.js
pause
